version: '2'
services:
    testreactwithscss-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/testReactWithScss/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=testReactWithScss
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
